services:

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    command: serve
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - app_network

  mathagent:
    build: .
    ports:
      - "7860:7860"
    depends_on:
      - ollama
    networks:
      - app_network

volumes:
  ollama_data:

networks:
  app_network: